-- Migration: water tracking + JTBD onboarding fields

ALTER TABLE users ADD COLUMN IF NOT EXISTS water_goal_ml INTEGER NOT NULL DEFAULT 2000;
ALTER TABLE users ADD COLUMN IF NOT EXISTS motivation VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS main_obstacle VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS food_preferences TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS meal_count INTEGER NOT NULL DEFAULT 4;

CREATE TABLE IF NOT EXISTS water_logs (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  amount_ml INTEGER NOT NULL,
  logged_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  date DATE NOT NULL DEFAULT CURRENT_DATE
);
